- name: Playbook to build OS and install Docker

  block:

    - name: Set service_file_path variable
      set_fact:
        service_file_path: /etc/systemd/system/auctopus_docker.service

    - name: Set controller working_directory variable
      set_fact:
        working_directory: "{{ auctopus_docker_dest_dir }}/automation/prod"
      when: deployment_type == "controller"

    - name: Set runner working_directory variable
      set_fact:
        working_directory: "{{ auctopus_docker_dest_dir }}/runnerserver/prod"
      when: deployment_type == "runner"

    - name: Adding Docker Prerequisites
      include_tasks: docker/install_docker_prerequisites.yml

    - name: Adding Docker and Compose packages
      include_tasks: docker/install_docker_and_compose.yml

    - name: Create Docker Service
      include_tasks: docker/create_docker_service.yml

    - name: Enable Auctopus Docker Service
      ansible.builtin.systemd:
        name: auctopus_docker
        enabled: yes
        state: reloaded
      become: yes

    - name: Run Docker Setup
      include_tasks: "{{ auctopus_docker_dest_dir }}/automation/prod/anisible_fresh_start.yml"
      when: deployment_type == "controller"

    - name: Run Docker Setup
      include_tasks: "{{ auctopus_docker_dest_dir }}/runnerserver/prod/anisible_fresh_start.yml"
      when: deployment_type == "runner"

    

    
