- name: Playbook to build OS and install Docker

  block:

    - name: Set service_file_path variable
      set_fact:
        service_file_path: /etc/systemd/system/auctopus_docker.service

    - name: Set lite working_directory variable
      set_fact:
        working_directory: "{{ auctopus_docker_dest_dir }}/lite"
      when: deployment_type == "lite"

    - name: Set development working_directory variable
      set_fact:
        working_directory: "{{ auctopus_docker_dest_dir }}/automation/prod_dev"
      when: deployment_type == "development"

    - name: Set runner working_directory variable
      set_fact:
        working_directory: "{{ auctopus_docker_dest_dir }}/runnerserver/prod"
      when: deployment_type == "runner"

    - name: Set license working_directory variable
      set_fact:
        working_directory: "{{ auctopus_docker_dest_dir }}/license/prod"
      when: deployment_type == "license"

    - name: Adding Docker and Compose packages
      include_tasks: docker/install_docker_and_compose.yml

    - name: Create Docker Service
      include_tasks: docker/create_docker_service.yml

    - name: Enable Auctopus Docker Service
      ansible.builtin.systemd:
        name: auctopus_docker
        enabled: yes
        state: reloaded
      become: yes
      ignore_errors: yes

    # - name: Change permissions of ansible_fresh_start.yml
    #   file:
    #     path: "{{ auctopus_docker_dest_dir }}/runnerserver/prod/ansible_fresh_start.yml"
    #     mode: '0777'
    #   become: yes

    # - name: Check if ansible_fresh_start.yml exists
    #   stat:
    #     path: "{{ auctopus_docker_dest_dir }}/runnerserver/prod/ansible_fresh_start.yml"
    #   register: ansible_fresh_start_file
    #   become: yes

    # - name: Debug the ansible_fresh_start_file variable
    #   debug:
    #     var: ansible_fresh_start_file

    # - name: Fail if ansible_fresh_start.yml does not exist
    #   fail:
    #     msg: "The file ansible_fresh_start.yml does not exist at {{ auctopus_docker_dest_dir }}/runnerserver/prod/ansible_fresh_start.yml"
    #   when: not ansible_fresh_start_file.stat.exists

    - name: Run Docker Setup
      include_tasks: "{{ auctopus_docker_dest_dir }}/automation/prod/ansible_fresh_start.yml"
      when: deployment_type == "controller"

    - name: Run Docker Setup
      include_tasks: "{{ auctopus_docker_dest_dir }}/lite/ansible_fresh_start.yml"
      when: deployment_type == "lite"

    - name: Run Docker Setup
      include_tasks: "{{ auctopus_docker_dest_dir }}/runnerserver/prod/ansible_fresh_start.yml"
      when: deployment_type == "runner"

    - name: Run Docker Setup
      include_tasks: "{{ auctopus_docker_dest_dir }}/license/prod/ansible_fresh_start.yml"
      when: deployment_type == "license"

    - name: Run Docker Setup
      include_tasks: "{{ auctopus_docker_dest_dir }}/automation/prod_dev/ansible_fresh_start.yml"
      when: deployment_type == "development"

    

    
