- name: Master Setup repository
  hosts: localhost
  gather_facts: yes

  vars_prompt:
    - name: deployment_type
      prompt: "Enter the deployment type (controller,runner)"
      private: no
    # - name: anisble_ssh_user
    #   prompt: "Enter the SSH username"
    #   private: no
    # - name: ansible_ssh_pass
    #   prompt: "Enter the SSH password"
    #   private: yes
    # - name: ansible_become_pass
    #   prompt: "Enter the sudo password"
    #   private: yes

  vars:
    # Linux Deployment repository
    linux_deployment_dest_dir: "{{ playbook_dir }}/linux_deployment"

    # Auctopus Docker repository
    auctopus_docker_dest_dir: "{{ playbook_dir }}/auctopus_docker"

    #Testing
    anisble_ssh_user: "automation"
    ansible_ssh_pass: "automation@321"
    ansible_become_pass: "automation@321"

  tasks:

    - name: Validate deployment type
      fail:
        msg: "Invalid deployment type. Please enter 'controller' or 'runner'."
      when: deployment_type not in ['controller', 'runner']
      
    - name: Check if execute_docker_script.yml exists
      stat:
        path: "{{ linux_deployment_dest_dir }}/execute_docker_script.yml"
      become: yes
      register: execute_docker_script

    - name: Include the execute_docker_script.yml playbook
      include_tasks: "{{ linux_deployment_dest_dir }}/execute_docker_script.yml"
      when: execute_docker_script.stat.exists

    
    - name: Delete the Linux Deployment repository
      ansible.builtin.file:
        path: "{{ linux_deployment_dest_dir }}"
        state: absent
      become: yes
    


    

