---
- name: Master Setup repository
  hosts: localhost
  become: yes
  vars_prompt:
    - name: "github_username"
      prompt: "Enter your GitHub username"
      private: no
    - name: "github_token"
      prompt: "Enter your GitHub personal access token"
      private: yes
  vars:
    # Linux Deployment repository
    repo_url: "https://github.com/auctopusGithub/linux_deployment.git"
    dest_dir: "{{ playbook_dir }}/linux_deployment"

    # Auctopus Docker repository
    auctopus_docker_repo_url: "https://github.com/auctopusGithub/auctopus_automation_dev.git"
    auctopus_docker_dest_dir: "{{ playbook_dir }}/auctopus_docker"

  tasks:
    - name: Ensure Git is installed
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Configure Git with GitHub token
      shell: |
        git config --global credential.helper store
        echo "https://{{ github_username }}:{{ github_token }}@github.com" > ~/.git-credentials

    - name: Clone the Linux Deployment repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: main

    - name: Clone the Auctopus Docker repository
      git:
        repo: "{{ auctopus_docker_repo_url }}"
        dest: "{{ auctopus_docker_dest_dir }}"
        version: prod

    - name: Execute the build_os_playbook_docker.yml playbook
      command: ansible-playbook build_os_playbook_docker.yml
      args:
        chdir: "{{ dest_dir }}"