- name: Master Setup repository
  hosts: all
  gather_facts: no

  vars:
    auctopus_docker_repo_url: "{{ lookup('env', 'AUCTOPUS_DOCKER_REPO_URL') }}"
    system_management_repo_url: "{{ lookup('env', 'SYSTEM_MANAGEMENT_REPO_URL') }}"
    ansible_ssh_user: "{{ lookup('env', 'ANSIBLE_SSH_USER') }}"
    ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_SSH_PASS') }}"
    ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}" 
    github_username: "{{ lookup('env', 'GITHUB_USERNAME') }}"
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    docker_token: "{{ lookup('env', 'DOCKER_TOKEN') }}"
    docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    deployment_type: "{{ lookup('env', 'DEPLOYMENT_TYPE') }}"
    server_port: "{{ lookup('env', 'SERVER_PORT') }}"
    server_ip: "{{ lookup('env', 'SERVER_IP') }}"
    static_playbook_dir: "/home/automation/automation"

    
  tasks:
    - debug:
        msg: "{{server_ip}}"

    - name: Set auctopus_docker_dest_dir variable
      set_fact:
        auctopus_docker_dest_dir: "{{ static_playbook_dir }}/auctopus_docker"

    - name: Set system_management_dest_dir variable
      set_fact:
        system_management_dest_dir: "{{ static_playbook_dir }}/system_management"

    - name: Debug the auctopus_docker_dest_dir variable
      debug:
        msg: "auctopus_docker_dest_dir is set to {{ auctopus_docker_dest_dir }}"

    # - name: Configure UFW based on deployment type
    #   include_tasks: configure_ufw.yml

    - name: Validate deployment type
      fail:
        msg: "Invalid deployment type. Please enter 'runner' or 'development' or 'license' or 'lite'."
      when: deployment_type not in ['runner', 'development', 'license', 'lite']

    # --------------------------------------------------------------

    # --------------------------------------------------------------
    # Configure Git & GitHub, Clone Auctopus Docker and System Management repositories
    
    - name: Configure Git with GitHub token
      shell: |
        git config --global credential.helper store
        echo "https://{{ github_username }}:{{ github_token }}@github.com" > ~/.git-credentials
      become: yes

    - name: Remove existing Auctopus Docker repository if present
      file:
        path: "{{ auctopus_docker_dest_dir }}"
        state: absent
        force: yes
      become: yes

    - name: Clone the Auctopus Docker repository
      git:
        repo: "{{ auctopus_docker_repo_url }}"
        dest: "{{ auctopus_docker_dest_dir }}"
        version: main
      become: yes
    
    - name: Remove existing System Management repository if present
      file:
        path: "{{ system_management_dest_dir }}"
        state: absent
        force: yes
      become: yes
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Clone the System Management repository
      git:
        repo: "{{ system_management_repo_url }}"
        dest: "{{ system_management_dest_dir }}"
        version: main
      become: yes
      when: deployment_type != 'runner' and deployment_type != 'license'

    # --------------------------------------------------------------

    # --------------------------------------------------------------
    # Get controller private and public IP from host

    - name: Get controller private IP from host
      command: ip route get 1.1.1.1
      register: ip_route_output
      changed_when: false
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Set controller_private_ip fact
      set_fact:
        controller_private_ip: "{{ ip_route_output.stdout.split('src')[1].split()[0] }}"
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Get controller public IP from host
      shell: curl -s https://api.ipify.org
      register: controller_public_ip_output
      changed_when: false
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Set controller_public_ip fact
      set_fact:
        controller_public_ip: "{{ controller_public_ip_output.stdout }}"
      when: deployment_type != 'runner' and deployment_type != 'license'

    # --------------------------------------------------------------

    # --------------------------------------------------------------
    # Development Env Setup
    - name: Replace value in backend .env file with server IP
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/prod_dev/env/backend.env"
        regexp: '^FRONTEND_HOST=.*$'
        line: 'FRONTEND_HOST={{ server_ip }}'
      become: yes
      when: deployment_type == 'development'

    - name: Replace value in backend .env file with server port
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/prod_dev/env/backend.env"
        regexp: '^FRONTEND_PORT=.*$'
        line: 'FRONTEND_PORT={{ server_port }}'
      become: yes
      when: deployment_type == 'development'

    - name: Replace value in frontend .env file with server IP
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/prod_dev/env/frontend.env"
        regexp: '^REACT_APP_BACKEND_HOST=.*$'
        line: 'REACT_APP_BACKEND_HOST={{ server_ip }}'
      become: yes
      when: deployment_type == 'development'

    - name: Update CONTROLLER_PRIVATE_IP in backend.env
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/prod_dev/env/backend.env"
        regexp: '^CONTROLLER_PRIVATE_IP=.*$'
        line: "CONTROLLER_PRIVATE_IP={{ controller_private_ip }}"
      become: yes
      when: deployment_type == 'development'

    - name: Update CONTROLLER_PUBLIC_IP in backend.env
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/prod_dev/env/backend.env"
        regexp: '^CONTROLLER_PUBLIC_IP=.*$'
        line: "CONTROLLER_PUBLIC_IP={{ controller_public_ip }}"
      become: yes
      when: deployment_type == 'development'

    - name: Set CONTROLLER_IP as CONTROLLER_PRIVATE_IP in backend.env
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/prod_dev/env/backend.env"
        regexp: '^CONTROLLER_IP=.*$'
        line: "CONTROLLER_IP={{ controller_private_ip }}"
      become: yes
      when: deployment_type == 'development'

    - name: Replace value in system management update_allowed_host.yml file with current deployment
      lineinfile:
        path: "{{ system_management_dest_dir }}/backend/system_management/ansible/update_allowed_host.yml"
        regexp: '^    auctopus_docker_dest_dir:.*$'
        line: '    auctopus_docker_dest_dir: "{{ static_playbook_dir }}/auctopus_docker/automation/prod_dev"'
      become: yes
      when: deployment_type == 'development'

    - name: Replace value in system management update_controller_ip.yml file with current deployment
      lineinfile:
        path: "{{ system_management_dest_dir }}/backend/system_management/ansible/update_controller_ip.yml"
        regexp: '^    auctopus_docker_dest_dir:.*$'
        line: '    auctopus_docker_dest_dir: "{{ static_playbook_dir }}/auctopus_docker/automation/prod_dev"'
      become: yes
      when: deployment_type == 'development'
    # --------------------------------------------------------------

    # --------------------------------------------------------------
    # Lite Env Setup

    - name: Replace value in backend .env file with server IP
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/lite/env/backend.env"
        regexp: '^FRONTEND_HOST=.*$'
        line: 'FRONTEND_HOST={{ server_ip }}'
      become: yes
      when: deployment_type == 'lite'

    - name: Replace value in backend .env file with server port
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/lite/env/backend.env"
        regexp: '^FRONTEND_PORT=.*$'
        line: 'FRONTEND_PORT={{ server_port }}'
      become: yes
      when: deployment_type == 'lite'

    - name: Replace value in frontend .env file with server IP
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/lite/env/frontend.env"
        regexp: '^REACT_APP_BACKEND_HOST=.*$'
        line: 'REACT_APP_BACKEND_HOST={{ server_ip }}'
      become: yes
      when: deployment_type == 'lite'

    - name: Update CONTROLLER_PRIVATE_IP in backend.env
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/lite/env/backend.env"
        regexp: '^CONTROLLER_PRIVATE_IP=.*$'
        line: "CONTROLLER_PRIVATE_IP={{ controller_private_ip }}"
      become: yes
      when: deployment_type == 'lite'

    - name: Update CONTROLLER_PUBLIC_IP in backend.env
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/lite/env/backend.env"
        regexp: '^CONTROLLER_PUBLIC_IP=.*$'
        line: "CONTROLLER_PUBLIC_IP={{ controller_public_ip }}"
      become: yes
      when: deployment_type == 'lite'

    - name: Set CONTROLLER_IP as CONTROLLER_PRIVATE_IP in backend.env
      lineinfile:
        path: "{{ auctopus_docker_dest_dir }}/automation/lite/env/backend.env"
        regexp: '^CONTROLLER_IP=.*$'
        line: "CONTROLLER_IP={{ controller_private_ip }}"
      become: yes
      when: deployment_type == 'lite'

    # --------------------------------------------------------------

    # --------------------------------------------------------------
    # Update system management .env file for system management

    - name: Update CONTROLLER_PRIVATE_IP in .env for system management
      lineinfile:
        path: "{{ system_management_dest_dir }}/backend/.env"
        regexp: '^CONTROLLER_PRIVATE_IP=.*$'
        line: "CONTROLLER_PRIVATE_IP={{ controller_private_ip }}"
      become: yes
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Update CONTROLLER_PUBLIC_IP in .env for system management
      lineinfile:
        path: "{{ system_management_dest_dir }}/backend/.env"
        regexp: '^CONTROLLER_PUBLIC_IP=.*$'
        line: "CONTROLLER_PUBLIC_IP={{ controller_public_ip }}"
      become: yes
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Set CONTROLLER_IP as CONTROLLER_PRIVATE_IP in .env for system management
      lineinfile:
        path: "{{ system_management_dest_dir }}/backend/.env"
        regexp: '^CONTROLLER_IP=.*$'
        line: "CONTROLLER_IP={{ controller_private_ip }}"
      become: yes
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Replace value in system_mangement .env file with deployment_type
      lineinfile:
        path: "{{ system_management_dest_dir }}/backend/.env"
        regexp: '^DEPLOYMENT_TYPE=.*$'
        line: 'DEPLOYMENT_TYPE={{ deployment_type }}'
      become: yes
      when: deployment_type != 'runner' and deployment_type != 'license'

    # --------------------------------------------------------------

    # --------------------------------------------------------------
    # Install Docker & Docker Compose, Create and Start Services

    - name: Run build_os_playbook_docker.yml 
      include_tasks: build_os_playbook_docker.yml
    
    - name: Set system_management_service_file_path variable
      set_fact:
        system_management_service_file_path: /etc/systemd/system/system_management.service
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Set system management working_directory variable
      set_fact:
        system_management_working_directory: "{{ system_management_dest_dir }}"
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Install python3-venv
      apt:
        name: python3-venv
        state: present
      become: yes

    - name: Run create_system_management_service.yml 
      include_tasks: create_system_management_service.yml
      when: deployment_type != 'runner' and deployment_type != 'license'

    - name: Run customize_machine.yml
      include_tasks: customize_machine.yml
