- name: Install Docker and Docker Compose on Ubuntu
  block:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: yes

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker’s official APT repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
      become: yes

    - name: Update apt package index (again)
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      become: yes

    - name: Enable and Start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
      become: yes

    - name: Install Docker Compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
        chmod +x /usr/local/bin/docker-compose
      become: yes


# - name: Install Docker and Docker Compose on Ubuntu
#   block:
#     - name: Update apt package index
#       ansible.builtin.apt:
#         update_cache: yes
#       become: yes

#     - name: Install Docker packages
#       ansible.builtin.apt:
#         name: 
#           - docker-ce
#           - docker-ce-cli
#           - containerd.io
#         state: present
#       become: yes
    
#     - name: Enable and Start Docker service
#       ansible.builtin.systemd:
#         name: docker
#         enabled: yes
#         state: started
#       become: yes

#     - name: Install Docker Compose
#       ansible.builtin.shell: |
#         curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
#         chmod +x /usr/local/bin/docker-compose
#       become: yes