- name: Install Docker Prerequisites
  block:      
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - software-properties-common
      become: yes
    
    - name: Add Docker GPG key
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      become: yes

    - name: Add Docker repository
      ansible.builtin.shell:
        cmd: |
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: yes