- name: Install Docker and Docker Compose on Ubuntu
  block:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Check if Docker Compose is installed
      ansible.builtin.command: docker-compose --version
      register: docker_compose_installed
      ignore_errors: yes

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Install Docker
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      become: yes
      when: docker_installed.rc != 0

    - name: Enable and Start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
      become: yes
      when: docker_installed.rc != 0

    - name: Install Docker Compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
        chmod +x /usr/local/bin/docker-compose
      become: yes
      when: docker_compose_installed.rc != 0