- name: Install Docker and Docker Compose on Ubuntu
  block:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Check if Docker Compose is installed
      ansible.builtin.command: docker compose version
      register: docker_compose_installed
      ignore_errors: yes

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Set up the Docker stable repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Update apt package index again
      ansible.builtin.apt:
        update_cache: yes
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Install Docker and Docker Compose
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
      state: present
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Enable and Start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
      when: docker_installed.rc != 0
  become: yes
