- name: Create Docker Service
  block:
    - name: Create Docker Service File
      ansible.builtin.shell:
        cmd: sudo touch /etc/systemd/system/auctopus_docker_runner.service && sudo chmod 644 /etc/systemd/system/auctopus_docker_runner.service

    - name: Insert Docker Service Configuration
      ansible.builtin.blockinfile:
        path: /etc/systemd/system/auctopus_docker_runner.service
        block: |
          [Unit]
          Description=Auctopus Docker Container
          After=network.target

          [Service]
          User=root
          Group=root
          WorkingDirectory=/home/auctopus/automation/auctopus_docker/runnerserver/prod
          ExecStart=/usr/local/bin/docker-compose -f docker-compose.runner.prod.yml up -d
          Restart=always
          RestartSec=10s

          [Install]
          WantedBy=multi-user.target

    - name: Reload Systemd Daemon
      ansible.builtin.shell:
        cmd: systemctl daemon-reload

    - name: Enable and Start Auctopus Docker service
      ansible.builtin.systemd:
        name: auctopus_docker_runner
        enabled: yes
        state: started
        
  become: yes


